apiVersion: v1
kind: Deployment
metadata:
  name: hello-v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello
        version: "v1"
    spec:
      containers:
        - name: hello
          image: naveen5035/hello:v1
          ports:
            - containerPort: 80
