apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http

  # Note here that we match both the app and the version
  selector:
    app: hello
    version: v1.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v1
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
      version: v1.0.0
  template:
    metadata:
      labels:
        app: hello
        version: v1.0.0
    spec:
      containers:
      - name: hello
        image: naveen5035/hello:v1
        ports:
        - name: http
          containerPort: 80
