apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v2
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
      version: v2
  template:
    metadata:
      labels:
        app: hello
        version: v2

    spec:
      containers:
      - name: hello
        image: naveen5035/hello:v2
        ports:
        - name: http
          containerPort: 80