apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 2
  strategy:
#     type: Recreate
#     type: RollingUpdate
#     rollingUpdate:
#        maxUnavailable: 0   # maxUnavailable define how many pods can be unavailable during the rolling update
#        maxSurge: 1        # how many pods we can add at a time
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: naveen5035/hello:v2
        ports:
        - containerPort: 80
